# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='hep.proto',
  package='',
  serialized_pb='\n\thep.proto\"=\n\nFourVector\x12\n\n\x02pt\x18\x01 \x02(\x01\x12\x0b\n\x03\x65ta\x18\x02 \x02(\x01\x12\t\n\x01\x45\x18\x03 \x02(\x01\x12\x0b\n\x03phi\x18\x04 \x02(\x01\"7\n\x08\x45lectron\x12\x18\n\x03kin\x18\x01 \x02(\x0b\x32\x0b.FourVector\x12\x11\n\tisolation\x18\x02 \x02(\x01\"3\n\x04Muon\x12\x18\n\x03kin\x18\x01 \x02(\x0b\x32\x0b.FourVector\x12\x11\n\tisolation\x18\x02 \x02(\x01\"2\n\x03Jet\x12\x18\n\x03kin\x18\x01 \x02(\x0b\x32\x0b.FourVector\x12\x11\n\tisolation\x18\x02 \x02(\x01\"_\n\x05\x45vent\x12\x14\n\x05muons\x18\x01 \x03(\x0b\x32\x05.Muon\x12\x1c\n\telectrons\x18\x02 \x03(\x0b\x32\t.Electron\x12\x12\n\x04jets\x18\x03 \x03(\x0b\x32\x04.Jet\x12\x0e\n\x06number\x18\x04 \x02(\x01\"$\n\nCollection\x12\x16\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x06.Event')




_FOURVECTOR = descriptor.Descriptor(
  name='FourVector',
  full_name='FourVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pt', full_name='FourVector.pt', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='eta', full_name='FourVector.eta', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='E', full_name='FourVector.E', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='phi', full_name='FourVector.phi', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=13,
  serialized_end=74,
)


_ELECTRON = descriptor.Descriptor(
  name='Electron',
  full_name='Electron',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='kin', full_name='Electron.kin', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='isolation', full_name='Electron.isolation', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=76,
  serialized_end=131,
)


_MUON = descriptor.Descriptor(
  name='Muon',
  full_name='Muon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='kin', full_name='Muon.kin', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='isolation', full_name='Muon.isolation', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=133,
  serialized_end=184,
)


_JET = descriptor.Descriptor(
  name='Jet',
  full_name='Jet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='kin', full_name='Jet.kin', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='isolation', full_name='Jet.isolation', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=186,
  serialized_end=236,
)


_EVENT = descriptor.Descriptor(
  name='Event',
  full_name='Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='muons', full_name='Event.muons', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='electrons', full_name='Event.electrons', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='jets', full_name='Event.jets', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='number', full_name='Event.number', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=238,
  serialized_end=333,
)


_COLLECTION = descriptor.Descriptor(
  name='Collection',
  full_name='Collection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='events', full_name='Collection.events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=335,
  serialized_end=371,
)

_ELECTRON.fields_by_name['kin'].message_type = _FOURVECTOR
_MUON.fields_by_name['kin'].message_type = _FOURVECTOR
_JET.fields_by_name['kin'].message_type = _FOURVECTOR
_EVENT.fields_by_name['muons'].message_type = _MUON
_EVENT.fields_by_name['electrons'].message_type = _ELECTRON
_EVENT.fields_by_name['jets'].message_type = _JET
_COLLECTION.fields_by_name['events'].message_type = _EVENT
DESCRIPTOR.message_types_by_name['FourVector'] = _FOURVECTOR
DESCRIPTOR.message_types_by_name['Electron'] = _ELECTRON
DESCRIPTOR.message_types_by_name['Muon'] = _MUON
DESCRIPTOR.message_types_by_name['Jet'] = _JET
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['Collection'] = _COLLECTION

class FourVector(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FOURVECTOR
  
  # @@protoc_insertion_point(class_scope:FourVector)

class Electron(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ELECTRON
  
  # @@protoc_insertion_point(class_scope:Electron)

class Muon(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MUON
  
  # @@protoc_insertion_point(class_scope:Muon)

class Jet(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JET
  
  # @@protoc_insertion_point(class_scope:Jet)

class Event(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVENT
  
  # @@protoc_insertion_point(class_scope:Event)

class Collection(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COLLECTION
  
  # @@protoc_insertion_point(class_scope:Collection)

# @@protoc_insertion_point(module_scope)
